# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('total_harga', models.BigIntegerField()),
                ('created_time', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('updated_time', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
