# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20191105_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksibarang',
            options={},
        ),
    ]
