# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_auto_20191105_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.TransaksiBarang'),
        ),
    ]
