# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_auto_20191105_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksibarang',
            name='jenis_transaksi',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='action_from',
            field=models.SmallIntegerField(choices=[('INIT', 'INIT'), ('PENYESUAIAN', 'PENYESUAIAN'), ('TRANSAKSI_SALES', 'TRANSAKSI_SALES')], default=0),
            preserve_default=False,
        ),
    ]
