# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_auto_20191107_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='action_from',
            field=models.SmallIntegerField(choices=[(0, 'INIT'), (1, 'PENYESUAIAN'), (2, 'TRANSAKSI_SALES')]),
        ),
    ]
